Repository OubaidaAkilan/JWT-Auth-App, pull requests merged in 2023-03, with the labels that each got.

#4 Write the documentaion about preparin the server.
  Backend/README.md
  Backend/package-lock.json
  Backend/package.json
Labels: documentation

#8 Auth
  Backend/README.md
  Backend/config/database.js
  Backend/middleware/auth/basicAuth.js
  Backend/middleware/auth/bearerAuth.js
  Backend/middleware/errorMiddleware.js
  Backend/middleware/globalErorrHandlingMiddleware.js
  Backend/models/userModel.js
  Backend/package-lock.json
  Backend/package.json
  Backend/routes/authRoutes.js
  Backend/routes/userRoutes.js
  Backend/server.js
  Backend/services/authService.js
  Backend/services/userService.js
  Backend/utils/authValidators/signupAuthValidator.js
  Backend/utils/authValidators/userAuthenticatBasic.js
  Backend/utils/authValidators/validateToken.js
  Backend/utils/validators/userValidators.js
Labels: enhancement

#9 We don't add anything, just apply prettier on folders.
  Backend/middleware/auth/aclAuth.js
  Backend/models/userModel.js
  Backend/routes/userRoutes.js
  Backend/server.js
  Backend/services/userService.js
  Backend/utils/validators/userValidators.js
Labels: Apply Prettier

#11 Config frontend
  Frontend/README.md
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.jsx
  Frontend/src/components/Input.jsx
  Frontend/src/components/login/Login.jsx
  Frontend/src/components/login/login.css
  Frontend/src/components/register/Register.jsx
  Frontend/src/components/register/register.css
  Frontend/src/container/login/Login.jsx
  Frontend/src/container/login/login.css
  Frontend/src/container/main/Main.jsx
  Frontend/src/container/register/Register.jsx
  Frontend/src/container/register/register.css
  Frontend/src/index.css
  Frontend/src/index.js
  Frontend/tailwind.config.js
Labels: enhancement, Refactoring

#15 Form validation, adding axios to the project & enhance the regex email input
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/api/axios.js
  Frontend/src/container/register/Register.jsx
Labels: enhancement, invalid

#13 Auth, Added CORS to the project
  Backend/README.md
  Backend/package-lock.json
  Backend/package.json
  Backend/server.js
  Frontend/src/container/register/Register.jsx
Labels: enhancement, invalid

#17 Try to fix the request from the server
  Backend/middleware/auth/basicAuth.js
  Backend/middleware/globalErorrHandlingMiddleware.js
  Backend/routes/authRoutes.js
  Backend/utils/authValidators/userAuthenticatBasic.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/api/AxiosInstance.js
  Frontend/src/api/axios.js
  Frontend/src/container/login/Login.jsx
  Frontend/src/container/register/Register.jsx
Labels: bug, Refactoring

#18 Refactor the structuer backend folder
  Backend/account/accountRoutes.js
  Backend/account/accountService.js
  Backend/account/signupAccountValidator.js
  Backend/middleware/aclAuthMiddleware.js
  Backend/middleware/auth/aclAuth.js
  Backend/middleware/auth/basicAuth.js
  Backend/middleware/auth/bearerAuth.js
  Backend/middleware/basicAuthMiddleware.js
  Backend/middleware/bearerAuthMiddleware.js
  Backend/routes/userRoutes.js
  Backend/server.js
  Backend/token/generateToken.js
  Backend/token/validateToken.js
  Backend/user/userRoutes.js
  Backend/user/userService.js
  Backend/user/userValidators.js
  Backend/user/validateUser.js
  Backend/utils/authValidators/validateToken.js
Labels: enhancement, Refactoring

#19 Delete some folder that we don't need
  Backend/routes/authRoutes.js
  Backend/utils/authValidators/userAuthenticatBasic.js
Labels: Refactoring

#20 Pass user's data from basicAuth middleware to login's response
  Backend/account/accountService.js
  Backend/middleware/basicAuthMiddleware.js
Labels: enhancement

#21 Auth, fix the validateToken and validateUser functions
  Backend/middleware/basicAuthMiddleware.js
  Backend/middleware/globalErorrHandlingMiddleware.js
  Backend/token/validateToken.js
  Backend/user/validateUser.js
Labels: enhancement

#22 form-validation, Edit the AxiosInstance, baseUrl and added withCredentials
  Frontend/src/api/AxiosInstance.js
Labels: Refactoring

#23 Form validation, Edit the format regex email and edit the register request.
  Frontend/src/container/login/Login.jsx
  Frontend/src/container/main/Main.jsx
  Frontend/src/container/register/Register.jsx
  Frontend/src/index.css
Labels: enhancement, Refactoring
